FROM python:3.10.4-alpine3.15

WORKDIR /app

RUN apk update \
&& apk add --no-cache gcc musl-dev postgresql-dev python3-dev libffi-dev \
&& pip install --upgrade pip

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY ./ ./

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
FROM ubuntu:latest

RUN apt update && apt upgrade -y && apt install python3 -y && apt install nmap -y && apt install python3-pip -y && apt install git -y && apt autoremove -y

RUN git clone https://github.com/DanielRTala/AplicacionesWebI_project.git

WORKDIR /EBC

RUN pip3 install -r requirements.txt


CMD python3 EBC.py


